formatter: "markdown table"

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: "./modules"

sections:
  hide: []
  show: []

output:
  file: README.md
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true